version: "3.8"
services:
  trackmania:
    image: evotm/trackmania:${SERVER_VERSION}
    restart: always
    ports:
      - ${SERVER_PORT}:2350/tcp
      - ${SERVER_PORT}:2350/udp
    expose:
      - "5000"
    volumes:
      - ../${USERDATA_DIR}:/server/UserData
    environment:
      MASTER_LOGIN: ${MASTER_LOGIN}
      MASTER_PASSWORD: ${MASTER_PASSWORD}
      XMLRPC_ALLOWREMOTE: True
      DEDICATED_CFG: ${DEDICATED_CFG}
      GAME_SETTINGS: ${GAME_SETTINGS}
      FORCE_IP_ADDRESS: ${FORCE_IP}:${SERVER_PORT}
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - ../Database:/var/lib/mysql
    expose:
      - "3306"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - mariadb
  evosc:
    image: evotm/evosc
    restart: always
    depends_on:
      - trackmania
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_NAME: ${DATABASE_NAME}
      DB_USER: root
      DB_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      RPC_IP: trackmania
      RPC_PORT: 5000
      RPC_LOGIN: SuperAdmin
      RPC_PASSWORD: SuperAdmin
      GAME_SETTINGS: ${GAME_SETTINGS}
    volumes:
      - ../${USERDATA_DIR}:/server/UserData
      - ../ControllerData/EvoSC/config:/controller/config
      - ../ControllerData/EvoSC/modules:/controller/modules