version: "3.8"
services:
  trackmania:
    image: evotm/trackmania:${SERVER_VERSION}
    restart: always
    ports:
      - ${SERVER_PORT}:2350/tcp
      - ${SERVER_PORT}:2350/udp
    expose:
      - "5000"
    volumes:
      - ../${USERDATA_DIR}:/server/UserData
    environment:
      MASTER_LOGIN: ${MASTER_LOGIN}
      MASTER_PASSWORD: ${MASTER_PASSWORD}
      XMLRPC_ALLOWREMOTE: True
      DEDICATED_CFG: ${DEDICATED_CFG}
      GAME_SETTINGS: ${GAME_SETTINGS}
      FORCE_IP_ADDRESS: ${FORCE_IP}:${SERVER_PORT}
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - ../Database:/var/lib/mysql
    expose:
      - "3306"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - mariadb
  pyplanet:
    image: uzurka/pyplanet-docker
    restart: always
    depends_on:
      - trackmania
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_NAME: ${DATABASE_NAME}
      DB_USER: root
      DB_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      DEDICATED_HOST: trackmania
      DEDICATED_PORT: 5000
      DEDICATED_USER: SuperAdmin
      DEDICATED_PASSWORD: SuperAdmin
      GAME_SETTINGS: ${GAME_SETTINGS}
      PYPLANET_OWNER: ${OWNER_LOGIN}
    volumes:
      - ../ControllerData/PyPlanet/base.py:/app/server/settings/base.py
      - ../ControllerData/PyPlanet/apps.py:/app/server/settings/apps.py