version: "3.8"
services:
  trackmania:
    image: evotm/trackmania:${SERVER_VERSION}
    restart: always
    ports:
      - ${SERVER_PORT}:2350/tcp
      - ${SERVER_PORT}:2350/udp
    expose:
      - "5000"
    volumes:
      - ./${USERDATA_DIR}:/server/UserData
    environment:
      DEDICATED_CFG: ${DEDICATED_CFG}
      GAME_SETTINGS: ${GAME_SETTINGS}
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: pyp
      MARIADB_ROOT_PASSWORD: PyPlaDatabase
    volumes:
      - ./Database:/var/lib/mysql
    expose:
      - "3306"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: PyPlaDatabase
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - mariadb
  pyplanet:
    image: greep/pyplanet
    restart: always
    depends_on:
      - trackmania
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_NAME: pyp
      DB_USER: root
      DB_PASSWORD: PyPlaDatabase
      RPC_IP: trackmania
      RPC_PORT: 5000
      RPC_LOGIN: SuperAdmin
      RPC_PASSWORD: SuperAdmin
      GAME_SETTINGS: ${GAME_SETTINGS}
      PYPLANET_OWNER: ${OWNER_LOGIN}
    volumes:
      - ./${USERDATA_DIR}:/server/UserData
      - ./ControllerData/PyPlanet:/app/server/